---
title: "TS"
author: "SUNMI JU"
date: "5/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", message=F, warning=F)

library(ftsa)
library(ggplot2)
library(kableExtra)
```

* COVID19 - 480일 2020.01.22부터 2021.05.15까지 일별 확진자
* SARS - 
* MERSE - 
* H1N1 - 

# Data Cleansing
```{r eval=FALSE}
print("Don't run me")
covid <- read.csv('../Data/COVID19.csv')
covid_ <- aggregate(. ~ Country, covid[2:ncol(covid)], sum)

colname <- as.character(as.Date(as.character(c(
  seq(200122,200131), seq(200201,200229), seq(200301,200331), 
  seq(200401,200430), seq(200501,200531), seq(200601,200630),
  seq(200701,200731), seq(200801,200831), seq(200901,200930),
  seq(201001,201031), seq(201101,201130), seq(201201,201231),
  seq(210101,210131), seq(210201,210228), seq(210301,210331),
  seq(210401,210430), seq(210501,210515))), "%y%m%d"))

sum(is.na(colname)) # Fine
colnames(covid_) <- c("Country", colname)

sars <- read.csv('../Data/SARS.csv')
sars$Date <- as.Date(sars$Date, "%Y.%m.%d")

h1n1 <- read.csv('../Data/H1N1.csv')
h1n1$Date <- as.Date(h1n1$Date, "%Y.%m.%d")

write.csv(covid_, '../Data/COVID19_.csv', row.names = FALSE)
```

# Make fts Object
- https://stackoverflow.com/questions/39507618/creating-fts-object-in-r
```{r}
covid <- read.csv('../Data/COVID19_.csv')

MakeFtsObject <- function(country, days){
  x <- seq(1, days, 1)
  total <- ncol(covid) - days*1 - 1
  nc <- as.numeric(total%/%days)
  y <- matrix(as.numeric(covid[covid$Country == country, 2:(nc*days+1)]), 
              ncol=nc, byrow=FALSE)
  covid_fts <- rainbow::fts(x = x, y = y, xname="Date", yname=paste(country, "new confimation cases by 20 days"))
  colnames(covid_fts$y) <- c(as.character(seq(1,nc)))
  rownames(covid_fts$y) <- c(as.character(seq(1,days)))
  
  return(covid_fts)
}

# Time Series Predict Plotting 1
FtsObjectPlot1 <- function(covid_fts, country, days, ymin, ymax){
  plot(covid_fts, col = gray(0.8), xlab = "Date", ylab = "new confirmed cases", 
       main = paste(country, "/ Predict daily new confirmed cases in", days, "days"), 
       ylim = c(min(covid_fts$y)*ymin, max(covid_fts$y)*ymax))
  plot(forecast(ftsm(covid_fts, order = 3), h = 1), col='red', lwd=2, add = TRUE, 
       ylim = c(min(covid_fts$y)*ymin, max(covid_fts$y)*ymax))
  legend("bottomright", paste0("1-", days, " days"), col = c("red"))
}

# Time Series Predict Plotting 2
### 전역변수 covid data 필요, predict 비교할 때 nc*days + 2 부터
FtsObjectPlot2 <- function(covid_fts, country, days, nc){
  covid_fts_pre <- forecast(ftsm(covid_fts, order = 3), h = 1, stationary=FALSE, method = "arima") # method = "ets"
  df <- data.frame(X = seq(nc*days + days*1),
                 Y = as.numeric(covid[covid$Country == country, 2:(nc*days+days*1+1)]),
                 Yhat = c(rep(NA, nc*days-1), covid[covid$Country == country, (nc*days+1)], as.vector(covid_fts_pre$mean$y)),
                 Lower = c(rep(NA, nc*days), as.vector(covid_fts_pre$lower$y)),
                 Upper = c(rep(NA, nc*days), as.vector(covid_fts_pre$upper$y)))

  ggplot(df) + geom_errorbar(aes(x=X, y=Yhat, ymin=Lower,ymax=Upper),color='pink', alpha=0.5, position="dodge",width=0.2) +
    geom_line(aes(x=X, y=Y), color='darkgrey') + geom_line(aes(x=X, y=Yhat), color='red') + theme_bw() + 
    ggtitle(paste(country, "/ Predict daily new confirmed cases in", days, "days")) + theme(plot.title = element_text(hjust=0.5, size=12, face="bold"))
}

FtsObjectPlot3<- function(covid_fts, country, days, nc, stationary, method, order, lambda){
  covid_fts_pre <- forecast(ftsm(covid_fts, order = order, lambda = lambda), h = 1, stationary=stationary, method = method) # method = "ets", 'order' is number of principle componenets
  df <- data.frame(X = seq(nc*days + days*1),
                 Y = as.numeric(covid[covid$Country == country, 2:(nc*days+days*1+1)]),
                 Yhat = c(rep(NA, nc*days-1), covid[covid$Country == country, (nc*days+1)], as.vector(covid_fts_pre$mean$y)),
                 Lower = c(rep(NA, nc*days), as.vector(covid_fts_pre$lower$y)),
                 Upper = c(rep(NA, nc*days), as.vector(covid_fts_pre$upper$y)))

  p <- ggplot(df) + geom_errorbar(aes(x=X, y=Yhat, ymin=Lower,ymax=Upper),color='pink', alpha=0.5, position="dodge",width=0.2) +
    geom_line(aes(x=X, y=Y), color='darkgrey') + geom_line(aes(x=X, y=Yhat), color='red') + theme_bw() + 
    ggtitle(paste(country, "/ Predict daily new confirmed cases in", days, "days")) + theme(plot.title = element_text(hjust=0.5, size=12, face="bold"))
  
  mae <- mean(abs(as.numeric(covid[covid$Country == country,(nc*days+2):((nc+1)*days+1)]) - as.vector(covid_fts_pre$mean$y)))
  
  print(p)
  return(mae)
}
```

# Make fts Object / Covid19 / 14 days
```{r}
days <- 14
total <- ncol(covid) - days*1 - 1
nc <- as.numeric(total%/%days)

country <- 'US' # 먼가 모델이 잘못됬나봄
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.5, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)
us_mae_14 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'ets', 3, 3)

country <- 'Korea, South'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.15)
FtsObjectPlot2(covid_fts, country, days, nc)
korea_mae_14 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'ets', 3, 5)

country <- 'China'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)
china_mae_14 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'arima', 3, 5)
# stationary=FALSE, method = "arima"

country <- 'Australia'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)
nz_mae_14 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'arima', 3, 10)

# MSE 비교
df_14 <- data.frame(country = c('US', 'Korea', 'China', 'Australia'),
                    method = c('ETS', 'ETS', 'ARIMA', 'ARIMA'),
           stationary = c('FALSE', 'FALSE', 'FALSE',  'FALSE'),
           number_of_PC = c(3, 3, 3, 3),
           lambda = c(3, 5, 4, 10),
           MAE = round(c(us_mae_14, korea_mae_14, china_mae_14, nz_mae_14),1))

kable(df_14, align = "c") %>% kable_styling(full_width=F)

```

# Make fts Object / Covid / 30 days
```{r}
days <- 30
total <- ncol(covid) - days*1 - 1
nc <- as.numeric(total%/%days)

country <- 'US'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.5, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)
us_mae_30 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'ets', 2, 5)

country <- 'Korea, South'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.15)
FtsObjectPlot2(covid_fts, country, days, nc)
korea_mae_30 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'ets', 3, 5)

country <- 'China'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)
china_mae_30 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'arima', 3, 5)

country <- 'Australia' # 'New Zealand'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)
nz_mae_30 <- FtsObjectPlot3(covid_fts, country, days, nc, FALSE, 'arima', 4, 5)

# MSE 비교
df_30 <- data.frame(country = c( 'US', 'Korea', 'China', 'Australia'),
                    method = c('ETS', 'ETS', 'ARIMA', 'ARIMA'),
           stationary = c( 'FALSE', 'FALSE', 'FALSE', 'FALSE'),
           number_of_PC = c(2, 3, 3, 4),
           lambda = c( 5, 5, 5, 5),
           MAE = round(c(china_mae_30, us_mae_30, korea_mae_30, nz_mae_30),1))

kable(df_30, align = "c") %>% kable_styling(full_width=F)
# https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html
```

# Make fts Object / 60 days - 포기
```{r eval=FALSE}
days <- 60
total <- ncol(covid) - days*1 - 1
nc <- as.numeric(total%/%days)

country <- 'China'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)

country <- 'US'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.5, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)

country <- 'Korea, South'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.15)
FtsObjectPlot2(covid_fts, country, days, nc)

country <- 'New Zealand'
covid_fts <- MakeFtsObject(country, days)
FtsObjectPlot1(covid_fts, country, days, 0.95, 1.05)
FtsObjectPlot2(covid_fts, country, days, nc)
```

## Clustering
```{r}
data(sim_ex_cluster)
cluster_result<-mftsc(X=sim_ex_cluster, alpha=0.99)
cluster_result$member.final

length(sim_ex_cluster)

```

