---
title: "CLUS_SUN"
author: "SUNMI JU"
date: "5/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", message=F, warning=F)
library(ggplot2)
library(kableExtra)
library(fda)
```

## Choose Basis Expansion
```{r}
covid <- read.csv('../Data/COVID19_.csv')
covid_ <- t(covid[2:ncol(covid)])
colnames(covid_) <- covid$Country

# make fd
grid = round(seq(0,480,length=dim(covid_)[1]))
bspline_basis <- create.bspline.basis(c(0,480), nbasis=21, norder=4) # cubic spline
bspline_far <- fdPar(bspline_basis, Lfdobj=2, lambda=1) # lambda가 클수록 패널티텀의 중요도가 높아 smooth해짐
fdobj <- smooth.basis(grid, covid_, bspline_far, fdnames=list('Days', 'Country', 'NewCases'))$fd

library(reshape)
plot(fdobj)

# Original Data
covid_m <- melt(covid, id=c("Country"))
covid_m$Date <- as.Date(gsub("X", "", covid_m$variable), "%Y.%m.%d")
ggplot(covid_m) + geom_line(aes(x = Date, y=value, color=Country), show.legend = FALSE) 

```

## funFEM
- BIC 기준(-49258.07), DkBk 모델 선택
- discriminative latent mixture (DLM) models (DkBk)
- Model Based Clustering
```{r}
library(funFEM)

# Clustering
clus_FEM_3 <- funFEM(fdobj,K=3, model='all') # choose best model
clus_FEM_3$model
clus_FEM_3$bic

# Visualization of the partition and the group means
par(mfrow=c(1,2))
plot(fdobj,col=clus_FEM_3$cls,lwd=2,lty=1)
fdmeans = fdobj; fdmeans$coefs = t(clus_FEM_3$prms$my)
plot(fdmeans,col=1:max(clus_FEM_3$cls),lwd=2)

# Table
df_FEM_3 <- data.frame(Country= covid$Country, Cluster=clus_FEM_3$cls)

clus1 = ''; clus2 = ''; clus3 = ''
for(i in 1:length(clus_FEM_3$cls)){
  if(clus_FEM_3$cls[i] == 1){
    clus1 = paste(clus1, covid$Country[i])
  }
  else if(clus_FEM_3$cls[i] == 2){
    clus2 = paste(clus3, covid$Country[i])
  }
  else{
    clus3 = paste(clus3, covid$Country[i])
  }
}

kable(data.frame(Cluster = c("Cluster 1", "Cluster 2", "Cluster 3"),
                 Country = c(clus1, clus2, clus3))) %>% kable_styling(full_width=F)
```

## funHDDC
- BIC 기준(-2828596), AKJBQKDK 모델 선택
- discriminative latent mixture (DLM) models (DkBk)
- Model Based Clustering
```{r}
library(funHDDC)

# Clustering
clus_HDDC_3 <- funHDDC(fdobj, K=3, model='all') # choose best model
clus_HDDC_3$model
clus_HDDC_3$BIC

plot(fdobj, col=clus_HDDC_3$class)
```

## fdakma
- kma jointly performs clustering and alignment of a functional dataset

```{r}
library(fdakma)

# 1개 제외
X = round(seq(0,479,length=dim(covid_)[1])) # X
Y0 <- as.matrix(covid[,-1], ncol=480)

Y1 <- matrix(0, nrow=nrow(covid), ncol=(ncol(covid)-2))
for(i in c(1:479)){
  Y1[,i] = Y0[,i+1] - Y0[,i]
}
Y1 <- Y1[,-480]

Y0 <- Y0[,-480]

X <- X[2:length(X)]
X <- t(X)
matplot(t(X), t(Y1), type='l')

# Example: result of kma function with 2 clusters, allowing affine transformation for the abscissas and considering 'd1.pearson' as similarity.method.
fdakma_example <- kma(
  x=X, y0=Y0, y1=Y1, n.clust = 2,
  warping.method = 'affine',
  similarity.method = 'd1.pearson',
  center.method = 'k-means',
  seeds = c(1,21)
)
kma.show.results(fdakma_example)
```

