---
title: "HW2_SUNMIJU"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", message=F, warning=F) 
```

```{r}
library(coda)

### Read Data ###
n=20; xbar=4; sigma=1
mu0 = 0; sigma0=10
dataList=list(n=n, xbar=xbar, sigma=sigma, mu0=mu0, sigma0=sigma0)

### Function to Compute Posterior Kernel ###
post.kernel = function(mu, dataList){
  post.kernel = exp(-0.5*(((dataList$xbar-mu)*sqrt(dataList$n)/dataList$sigma)^2
                          +((mu-dataList$mu0)/dataList$sigma0)^2))
  return(post.kernel)
}

### Function to Perform Random Walk Metropolis ###
Metro = function(nsim, mu.init, delta, dataList){
  mu.samples = mu.init
  mu.curr = mu.init
  
  for(iter in 1:nsim){
    mu.prop = rnorm(1, mean=mu.curr, sd=delta)
    alpha = min(1, post.kernel(mu.prop, dataList)/post.kernel(mu.curr, dataList))
    
    u = runif(1)
    mu.next = mu.prop*(u<alpha) + mu.curr*(u>alpha)
    mu.samples = rbind(mu.samples, mu.next)
    mu.curr = mu.next
  }
  return(mu.samples)
}

### Simulation , 3 chains ###
delta = 0.2
nsim = 10000
n.chains = 3

mu.Samples = matrix(0, nsim, n.chains)

for(i in 1:n.chains){
  mu.init = rnorm(1, mu0, 2)
  mu.Samples[,i] = Metro(nsim-1, mu.init, delta, dataList)
}
```

### 경로그림
```{r}
nwarm = 500; nsim = 10000
plot(mu.Samples[(nwarm+1):nsim, 1], xlab = "itertation", ylab = "sample", type = "l", main = "", sub="(b)")
lines(mu.Samples[(nwarm+1):nsim, 2], col=2)
lines(mu.Samples[(nwarm+1):nsim, 3], col=3)
```

### 사후밀도함수
```{r, fig.height=3.5, fig.width=8.5}
par(mfrow = c(1,2))
nwarm = 0; nsim=200
plot(density(mu.Samples[(nwarm+1):nsim, 1]), xlab="mu", ylab="posterior density", main=paste("nwarm:", nwarm, "/ nsim:", nsim), sub="(a)", ylim=c(-0.3, 1.9), cex.main=0.8)
lines(density(mu.Samples[(nwarm+1):nsim,2]), col=2)
lines(density(mu.Samples[(nwarm+1):nsim,3]), col=3)

nwarm = 500; nsim=10000
plot(density(mu.Samples[(nwarm+1):nsim, 1]), xlab="mu", ylab="posterior density", main=paste("nwarm:", nwarm, "/ nsim:", nsim), sub="(b)", ylim=c(-0.3, 1.9), cex.main=0.8)
lines(density(mu.Samples[(nwarm+1):nsim,2]), col=2)
lines(density(mu.Samples[(nwarm+1):nsim,3]), col=3)
```

### Gelman 상수
```{r, fig.height=3.5, fig.width=4.5}
mu.Samples.default = mcmc(mu.Samples[1:200,])
mu1.codaSamples = mcmc.list(list(mu1.Samples[,1], mu1.Samples[,2], mu1.Samples[,3]))

mu2.Samples = mcmc(mu.Samples[501:10000,])
mu2.codaSamples = mcmc.list(list(mu2.Samples[,1], mu2.Samples[,2], mu2.Samples[,3]))

mu3.Samples = mcmc(mu.Samples[2001:10000,])
mu3.codaSamples = mcmc.list(list(mu3.Samples[,1], mu3.Samples[,2], mu3.Samples[,3]))

gelman.plot(mu1.codaSamples, col=c("black", "blue"), main="iter: 1-200")
gelman.plot(mu2.codaSamples, col=c("black", "blue"), main="iter: 501-10000")
gelman.plot(mu3.codaSamples, col=c("black", "blue"), main="iter: 2001-10000")
```



