---
title: "HW1_SUNMIJU"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", message=F, warning=F) 
```

## Metropolis-Hastings 방법1
```{r}
theta = c(1:5)
prob = c(1,3,8,5,3)/20

prob.ratio = function(theta1, theta2, theta, prob){
  ind1 = which(theta == theta1)
  ind2 = which(theta == theta2)
  return(prob[ind1]/prob[ind2])
}
N = 50000
theta.curr=2
theta.Samples=c(1:N)*0
theta.Samples[1]=theta.curr

## Simulation-1 ##
for(iter in 1:(N-1)){
  theta.prop = ifelse(runif(1)<0.5, theta.curr+1, theta.curr-1)
  if(theta.prop < 1 || theta.prop > 5){ # 나올 수 없는 후보값일 때, 현재값을 선택
    theta.prop = theta.curr
    theta.prop = round(theta.prop, 0)
  }
  alpha.star = prob.ratio(theta.prop, theta.curr, theta, prob)
  alpha = min(1, alpha.star)
  theta.next = ifelse(runif(1)<alpha, theta.prop, theta.curr)
  
  theta.Samples[iter+1] = theta.next
  theta.curr = theta.next
}

## End Simulation-1
par(mfrow=c(1,2))
hist(rep(theta,c(1,3,8,5,3)), breaks=c(0,1,2,3,4,5), width=0.1, prob=T, main="True Probability", cex.main=0.8, xlab="theta")
hist(theta.Samples[501:N], breaks=c(0,1,2,3,4,5), prob=T, main="M-H Sampling Method1", cex.main=0.8, xlab="theta")
par(mfrow=c(1,1))
```
<br><br>

## Metropolis-Hastings 방법2
```{r}
theta = c(1:5)
prob = c(1,3,8,5,3)/20

prob.ratio = function(theta1, theta2, theta, prob){
  ind1 = which(theta == theta1)
  ind2 = which(theta == theta2)
  return(prob[ind1]/prob[ind2])
}
N = 50000
theta.curr=2
theta.Samples=c(1:N)*0
theta.Samples[1]=theta.curr

## Simulation-2 ##
for(iter in 1:(N-1)){
  theta.prop = sample(theta, 1)
  theta.prop = round(theta.prop, 0)
  
  alpha.star = prob.ratio(theta.prop, theta.curr, theta, prob)
  alpha = min(1, alpha.star)
  theta.next = ifelse(runif(1)<alpha, theta.prop, theta.curr)
  
  theta.Samples[iter+1] = theta.next
  theta.curr = theta.next
}

## End Simulation-2
par(mfrow=c(1,2))
hist(rep(theta,c(1,3,8,5,3)), breaks=c(0,1,2,3,4,5), width=0.1, prob=T, main="True Probability", cex.main=0.8, xlab="theta")
hist(theta.Samples[501:N], breaks=c(0,1,2,3,4,5), prob=T, main="M-H Sampling Method2", cex.main=0.8, xlab="theta")
par(mfrow=c(1,1))
```
<br><br>

## Metropolis-Hastings 방법3
```{r}
theta = c(1:5)
prob = c(1,3,8,5,3)/20
prob.prop = c(0.1, 0.1, 0.2, 0.3, 0.3)

prob.ratio = function(theta1, theta2, theta, prob){
  ind1 = which(theta == theta1)
  ind2 = which(theta == theta2)
  return(prob[ind1]/prob[ind2])
}
N = 50000
theta.curr=2
theta.Samples=c(1:N)*0
theta.Samples[1]=theta.curr

## Simulation-3 ##
for(iter in 1:(N-1)){
  theta.prop = sample(theta, 1, prob=prob.prop) # proposition
  theta.prop = round(theta.prop, 0)
  
  alpha.star = prob.ratio(theta.prop, theta.curr, theta, prob)*
    prob.ratio(theta.curr, theta.prop, theta, prob.prop)
  alpha = min(1, alpha.star)
  theta.next = ifelse(runif(1)<alpha, theta.prop, theta.curr)
  
  theta.Samples[iter+1] = theta.next
  theta.curr = theta.next
}

## End Simulation-3
par(mfrow=c(1,2))
hist(rep(theta,c(1,3,8,5,3)), breaks=c(0,1,2,3,4,5), width=0.1, prob=T, main="True Probability", cex.main=0.8, xlab="theta")
hist(theta.Samples[501:N], breaks=c(0,1,2,3,4,5), prob=T, main="M-H Sampling Method3", cex.main=0.8, xlab="theta")
par(mfrow=c(1,1))
```

